### ISSUE TITLE
 'NoneType' object has no attribute 'display_version_or_commit'

### ISSUE THREAD

**Issue by thawizard** [custom-components/hacs#409] opened 2019-08-12 13:51 UTC
## Version of HACS
0.13.0

## Describe the bug
Problem persists since 0.13.0 
'Places' Integration keeps disappearing from HACS overview.

and when clicking on any(most) plugin or integration in HACS, it gives following error:

> 'NoneType' object has no attribute 'display_version_or_commit'

Reloading HACS or choosing 'HACS available version: next' will temporarily solve the problem until next restart. 

## Debug log

_2019-08-12 15:26:19 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 169, in startup_tasks
    self.data.write()
  File "/config/custom_components/hacs/hacsbase/data.py", line 63, in write
    "version_type": repository.display_version_or_commit,
AttributeError: 'NoneType' object has no attribute 'display_version_or_commit'_

Might have something to do with #404

**Comment by sreknob** [comment] 2019-08-12 14:52
I'm also seeing 
`WARNING (MainThread) [custom_components.hacs.template] Error rendering info template argument of type 'NoneType' is not iterable`
Agree it probably is due to the template in #404

**Comment by fredamn76** [comment] 2019-08-12 15:11
I have this exat issue sense 0.13.0. I run the latest Hassio build.

**Comment by tnagels** [comment] 2019-08-13 16:11
Same here!

**Comment by jmutnick** [comment] 2019-08-13 21:29
I also have this same problem.

**Comment by ludeeus** [comment] 2019-08-13 21:31
Which problem?

The OP here has posted 2 separate issues in this one...

**Comment by jmutnick** [comment] 2019-08-13 21:34
File "/home/pi/.homeassistant/custom_components/hacs/hacsbase/data.py", line 63, in write
    "version_type": repository.display_version_or_commit,
AttributeError: 'NoneType' object has no attribute 'display_version_or_commit'

**Comment by ludeeus** [comment] 2019-08-13 21:37
That should not be possible... 🤔

**Comment by thawizard** [comment] 2019-08-13 22:35
> The OP here has posted 2 separate issues in this one...

I just think they are interlocked. Places works fine, it just appears as uninstalled in HACS. 
It might be resolved if that AttributeError gets solved. 

I can open most Plugins/Integrations by opening/refreshing them in a new tab (/hacsweb/9bab2dda-a1fd-4438-9..) but not always.

**Comment by holdestmade** [comment] 2019-08-14 07:16
I too have the same problems

On startup, in log:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 169, in startup_tasks
    self.data.write()
  File "/config/custom_components/hacs/hacsbase/data.py", line 63, in write
    "version_type": repository.display_version_or_commit,
AttributeError: 'NoneType' object has no attribute 'display_version_or_commit'
```

Also, in STORE, if you click on an item, you get the error message:

'NoneType' object has no attribute 'display_version_or_commit'

If I click back, then the same item I can view the item and install etc

**Comment by nelbs** [comment] 2019-08-14 14:50
Got the same error:

```
NameError: name 'targetoption' is not defined
2019-08-14 16:33:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/__init__.py", line 192, in recuring_tasks_installed
    self.data.write()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/data.py", line 63, in write
    "version_type": repository.display_version_or_commit,
AttributeError: 'NoneType' object has no attribute 'display_version_or_commit'
```

**Comment by ludeeus** [comment] 2019-08-14 16:36
can one of you share (with hastebin **not** paste here) the contents of `.storage/hacs.repositories` and `hacs.installed`?

**Comment by jmutnick** [comment] 2019-08-14 16:43
I don't have access to that from work, but can get it to you when I get home.

**Comment by jmutnick** [comment] 2019-08-14 16:46
And I've never used hastebin, so it may take some learning.

**Comment by iantrich** [comment] 2019-08-14 17:15
doesn't have to necessarily be hastebin, just somewhere to share the log in a more readable format. Could also use gist.github.com

**Comment by caiosweet** [comment] 2019-08-14 17:29
https://hastebin.com/qojuharoho.json

https://hastebin.com/pupojuhico.json

**Comment by ludeeus** [comment] 2019-08-14 18:06
Looks like the root of the issue is repositories that have moved locations.

Like `Rocka84/dual-gauge-card`, and it looks like the error goes away for good when searching for and opening `dual-gauge-card` in the store.

**Comment by ludeeus** [comment] 2019-08-14 18:07
`places` are probably one more.

**Comment by jmutnick** [comment] 2019-08-14 21:35
https://hastebin.com/umipixazet

https://hastebin.com/vihajiluqu

**Comment by ludeeus** [comment] 2019-08-15 13:24
Rocka84/dual-gauge-card and places has been "fixed" by adding them to the blacklist.
Should reach your installations within 8h

**Comment by jmutnick** [comment] 2019-08-16 20:43
That still hasn't fixed it for me.

**Comment by nelbs** [comment] 2019-08-17 07:21
Uninstalling and reinstall all cards and plugins including hacs solved the problem (for now?)

**Comment by ludeeus** [comment] 2019-08-17 07:41
Fixed in https://github.com/custom-components/hacs/releases/tag/0.13.2

**Closed by ludeeus** 2019-08-17 07:41 UTC
Labels: Bug
