### ISSUE TITLE
Installed Components Not Listed After HA Restart

### ISSUE THREAD

**Issue by garyak** [custom-components/hacs#729] opened 2019-10-22 13:15 UTC
## Version of HACS
0.15.10

## Describe the bug
Installed components don't appear to be saved. Following an HA restart, all installed components, excluding HACS itself, vanish in the Overview tab.

Content of the hacs.installed file is this both before and after components are installed:
```
{
    "data": {},
    "schema": "5"
}
```

## Debug log

```text
2019-10-22 06:51:23 DEBUG (MainThread) [hacs.http] Endpoint (store) called
2019-10-22 06:51:27 INFO (MainThread) [engineio.client] Sending packet PING data None
2019-10-22 06:51:27 INFO (MainThread) [engineio.client] Received packet PONG data None
2019-10-22 06:51:49 DEBUG (MainThread) [hacs.http] Endpoint (repository) called
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.data] Saving data
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.backup] Backup for /config/.storage/hacs.hacs, created in /tmp/hacs_backup/hacs.hacs
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.backup] Backup dir /tmp/hacs_backup/ cleared
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.backup] Backup for /config/.storage/hacs.installed, created in /tmp/hacs_backup/hacs.installed
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.backup] Backup dir /tmp/hacs_backup/ cleared
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.data] Save failed!
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.data] Number of installed repositories does not match the number of stored repositories [1 vs 4]
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.data] Saving data
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.backup] Backup for /config/.storage/hacs.hacs, created in /tmp/hacs_backup/hacs.hacs
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.backup] Backup dir /tmp/hacs_backup/ cleared
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.backup] Backup for /config/.storage/hacs.installed, created in /tmp/hacs_backup/hacs.installed
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.backup] Backup dir /tmp/hacs_backup/ cleared
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.data] Save failed!
2019-10-22 06:51:51 DEBUG (MainThread) [hacs.data] Number of installed repositories does not match the number of stored repositories [1 vs 4]
2019-10-22 06:51:52 INFO (MainThread) [engineio.client] Sending packet PING data None
2019-10-22 06:51:53 INFO (MainThread) [engineio.client] Received packet PONG data None
2019-10-22 06:51:53 DEBUG (MainThread) [hacs.api] Endpoint (repository_install) called
2019-10-22 06:51:55 DEBUG (MainThread) [hacs.repository.plugin.nervetattoo.simple-thermostat] Downloading simple-thermostat.js
2019-10-22 06:51:55 DEBUG (MainThread) [hacs.download.downloader] Donwloading https://github.com/nervetattoo/simple-thermostat/releases/download/0.28.0/simple-thermostat.js
2019-10-22 06:51:55 INFO (MainThread) [engineio.client] Received packet MESSAGE data 2["device-data updated","2-f4019b556f8f10bb6412f5dade628923"]
2019-10-22 06:51:55 INFO (MainThread) [socketio.client] Received event "device-data updated" [/]
2019-10-22 06:51:55 INFO (MainThread) [engineio.client] Received packet MESSAGE data 2["device-data removed",[{"ok":true,"id":"b4e44d1e060045b2e28fe30fc282a5b1","rev":"2-b2ddac052a23dafa25237e480c749e58"}]]
2019-10-22 06:51:55 INFO (MainThread) [socketio.client] Received event "device-data removed" [/]
2019-10-22 06:51:56 INFO (MainThread) [engineio.client] Received packet MESSAGE data 2["device-data removed",{"cache-control":"must-revalidate","connection":"close","content-type":"application/json","date":"Tue, 22 Oct 2019 12:51:54 GMT","x-cloudant-action":"cloudantnosqldb.data-document.write","x-cloudant-cost-write":"1","x-couch-request-id":"562df8a11f","x-frame-options":"DENY","strict-transport-security":"max-age=31536000","x-content-type-options":"nosniff","x-cloudant-request-class":"write","x-cloudant-backend":"bm-cc-us-south-20","via":"1.1 lb1.bm-cc-us-south-20 (Glum/1.82.3)","statusCode":201,"uri":"https://78a8cc5e-04af-4d62-9a35-0a08d6e56224-bluemix:b9773c947dee3c33b981fcb9a009d2f66bb3119a4df34e3236ddfeed65c9a544@78a8cc5e-04af-4d62-9a35-0a08d6e56224-bluemix.cloudant.com/ambient-prod-2/_bulk_docs"}]
2019-10-22 06:51:56 INFO (MainThread) [socketio.client] Received event "device-data removed" [/]
2019-10-22 06:51:58 DEBUG (MainThread) [hacs.download.save] Saving /config/www/community/simple-thermostat/simple-thermostat.js
2019-10-22 06:51:58 INFO (MainThread) [hacs.repository.plugin.nervetattoo.simple-thermostat] download of simple-thermostat.js complete
2019-10-22 06:51:58 DEBUG (MainThread) [hacs.data] Saving data
2019-10-22 06:51:58 DEBUG (MainThread) [hacs.backup] Backup for /config/.storage/hacs.hacs, created in /tmp/hacs_backup/hacs.hacs
2019-10-22 06:51:58 DEBUG (MainThread) [hacs.backup] Backup dir /tmp/hacs_backup/ cleared
2019-10-22 06:51:58 DEBUG (MainThread) [hacs.backup] Backup for /config/.storage/hacs.installed, created in /tmp/hacs_backup/hacs.installed
2019-10-22 06:51:58 DEBUG (MainThread) [hacs.backup] Backup dir /tmp/hacs_backup/ cleared
2019-10-22 06:51:58 DEBUG (MainThread) [hacs.data] Save failed!
2019-10-22 06:51:58 DEBUG (MainThread) [hacs.data] Number of installed repositories does not match the number of stored repositories [1 vs 5]
2019-10-22 06:51:58 DEBUG (MainThread) [hacs.http] Endpoint (repository) called
2019-10-22 06:52:02 DEBUG (MainThread) [hacs.http] Endpoint (overview) called
```
Before:
![hacs](https://user-images.githubusercontent.com/47036329/67288832-dbb93600-f49a-11e9-8ef2-2d9f24141504.jpg)

After:
![hacs1](https://user-images.githubusercontent.com/47036329/67288955-0d320180-f49b-11e9-8da0-3c98b41d2806.jpg)

**Comment by ludeeus** [comment] 2019-10-22 13:26
Upload all the `hacs` files from `.storage`

**Comment by walthowd** [comment] 2019-10-22 13:34
Some other weirdness going on here too:
https://www.reddit.com/r/homeassistant/comments/dl4wdb/hacs_keeps_committing_suicide_any_ideas_on_whats/

**Comment by ludeeus** [comment] 2019-10-22 13:38
@walthowd That is not relevant, open a separate issue here https://github.com/custom-components/hacs/issues/new/choose

**Comment by garyak** [comment] 2019-10-22 13:40
Here are the current files:
[hacs.zip](https://github.com/custom-components/hacs/files/3755988/hacs.zip)

**Comment by ludeeus** [comment] 2019-10-22 13:44
You have only "hacs" showing as installed in `hacs.repositories`.
That does not match your error message, did you remove these files?

**Comment by garyak** [comment] 2019-10-22 13:54
I did not. I reinstalled the components, restarted HA, then reopened Community. I've repeated this three times now with identical results.

**Comment by ludeeus** [comment] 2019-10-22 13:58
Yeah, that will not work until the issue is solved.

**Comment by ludeeus** [comment] 2019-10-22 14:23
Good new/bad news

It's fixed in 0.15.11, which is now live.
But unless you have a backup of your `hacs.repositories.` you will need to "reinstall" your elements after you have upgraded.

**Comment by garyak** [comment] 2019-10-22 14:59
Updated to 0.15.11. Elements now remain on the overview tab. Background taskbar is a bit sticky on Firefox. I know, I know, different issue :-)

**Comment by ludeeus** [comment] 2019-10-22 15:07
That issue should be gone in the new (experimental) UI.

**Closed by ludeeus** 2019-10-22 15:07 UTC
