### ISSUE TITLE
Feature Request | Voting on components/plugins 

### ISSUE THREAD

**Issue by AalianKhan** [custom-components/hacs#302] opened 2019-07-19 00:25 UTC
**Is your feature request related to a problem? Please describe.**
I love HACS. Not fustrated
**Describe the solution you'd like**
Adding a voting  system to HACS to see which are the most popular components/plugins
**Describe alternatives you've considered**

**Additional context**

**Comment by ludeeus** [comment] 2019-07-21 07:57
Duplicate of https://github.com/custom-components/hacs/issues/229

**Closed by ludeeus** 2019-07-21 07:57 UTC
Labels: Will not add
