### ISSUE TITLE
Links to "issues" for repos (including HACS) are 404

### ISSUE THREAD

**Issue by dlashua** [custom-components/hacs#336] opened 2019-07-24 14:19 UTC
## Version of HACS
0.12.1

## Describe the bug
Links to "issues" for repos (including HACS) are 404. The link is found in the "hamburger menu" in the top right of every installable.

**Comment by ludeeus** [comment] 2019-07-24 14:41
duplicate of #324

**Closed by ludeeus** 2019-07-24 14:41 UTC
