### ISSUE TITLE
Mark all "new" as seen

### ISSUE THREAD

**Issue by fredrikbaberg** [custom-components/hacs#224] opened 2019-07-04 09:19 UTC
**Is your feature request related to a problem? Please describe.**
I scrolled through the "store" tab, installed what I was interested in, and then configured the components and cards. When I want to see if there are new features, it seems everything I have not opened are marked as "new" (or at least most of them), which leaves me with a mix with new and "unopened" items.

**Describe the solution you'd like**
A "Mark all as seen" button, so that I don't have to open each to remove the "new" flag from all entries.

**Describe alternatives you've considered**
Not sure of location, could be in Store or under settings.

**Additional context**

**Comment by ludeeus** [comment] 2019-07-04 09:27
duplicate of https://github.com/custom-components/hacs/issues/214

**Closed by ludeeus** 2019-07-04 09:27 UTC
Labels: Will not add
