### ISSUE TITLE
Hacs not working on 0.94.3

### ISSUE THREAD

**Issue by xMrVizzy** [custom-components/hacs#84] opened 2019-06-13 18:54 UTC
## Version of HACS

0.6.0

## Describe the bug

Bug: HACS not working on 0.94.3 Home Assistant

## Debug log

```text

Add your logs here.

2019-06-13 23:47:09 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

2019-06-13 23:47:09 ERROR (MainThread) [homeassistant.config] Package component_homeassistant setup failed. Component hacs unable to import (See /config/packages/components/component_homeassistant.yaml:3). 

```

**Comment by ludeeus** [comment] 2019-06-13 19:00
Duplicate of https://github.com/custom-components/hacs/issues/48

**Closed by ludeeus** 2019-06-13 19:00 UTC
Labels: Wont Fix
