### ISSUE TITLE
HACS does not start

### ISSUE THREAD

**Issue by frayberen** [custom-components/hacs#503] opened 2019-09-06 15:44 UTC
## Version of HACS
0.13.2

## Describe the bug
HACS does not start suddenly. 
Right now I have installed HASSIO v 0.98.4
Previously it worked correctly. Any solution for this?

## Debug log

```text

2019-09-06 17:04:12 CRITICAL (MainThread) [hacs.data] [Expecting value: line 1 column 1 (char 0)] Restore Failed!

```

**Comment by t0bse** [comment] 2019-09-06 16:58
same here.

**Comment by ludeeus** [comment] 2019-09-06 17:02
duplicate of https://github.com/custom-components/hacs/issues/476

**Closed by ludeeus** 2019-09-06 17:02 UTC
