### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by mclaudiopt** [custom-components/hacs#50] opened 2019-06-03 12:36 UTC
hello
i have installed this custom repository
thomasloven/lovelace-slider-entity-row

![image](https://user-images.githubusercontent.com/48178294/58802125-43fa9e80-8604-11e9-9c50-509c940dd9b0.png)

after installing all my cards give error

![image](https://user-images.githubusercontent.com/48178294/58802150-5543ab00-8604-11e9-86f7-66cd51c31901.png)

the JS was installed
![image](https://user-images.githubusercontent.com/48178294/58802187-6d1b2f00-8604-11e9-8cf0-8193259d6e06.png)

i have added the url in UI-lovelace
![image](https://user-images.githubusercontent.com/48178294/58802211-858b4980-8604-11e9-9ca5-af6634761676.png)

what am i doing wrong?
thanks

**Comment by ludeeus** [comment] 2019-06-03 13:29
First code should not be pasted as screenshots ;)
it also states whats wrong in the log file ;)
Remove the last "lovelace-" part of the filename in the filename you have under resources, and it will work

**Comment by mclaudiopt** [comment] 2019-06-03 13:35
hi
yes it worked now ! but in case of update i will have to change the file name always or not?

btw, how can i contribute with other repositories so that anyone can use them directly?

examples:

  - type: js
    url: /local/tracker-card.js?v=0
  - type: js
    url: /customcards/github/thomasloven/card-tools.js?track=true
  - type: js
    url: /local/plugins/card-modder.js?v=1
  - type: module
    url: /local/timer-card.js?v=0
  - type: js
    url: /local/fold-entity-row.js?v=0
  - type: module
    url: /customcards/github/maykar/compact-custom-header.js?track=true

**Comment by ludeeus** [comment] 2019-06-03 14:01
No need to change for update.
Currently you can only add things to your install, I think all of the cards on your list is supported, you just need to add the repos :)

**Comment by ludeeus** [comment] 2019-06-03 14:58
Duplicate of #47

**Closed by ludeeus** 2019-06-03 14:58 UTC
Labels: Bug: minor
